# Site settings
title: Nudibranchs of southwest Australia
description: "An incomplete field guide to nudibranchs and allied clades of southwest Australia."
url: "https://mpfl.github.io/nudis/"
author:
  name: "Matthias Liffers"
  email: "m@tthi.as"
  url: "http://ma.tthi.as/"

collections:
  species:
  observations: