# Site settings
title: Nudibranchs of southwest Australia
description: "An incomplete field guide to nudibranchs and allied clades of southwest Australia."
url: "https://nudi.app/"
baseurl: ""
author:
  name: "Matthias Liffers"
  email: "m@tthi.as"
  url: "http://ma.tthi.as/"

collections:
  species:
    output: true
    permalink: /species/:name
  observations:
    output: true
    permalink: /observations/:name

defaults:
  - scope:
      path: "_species"
      type: "species"
    values:
      layout: "species"
  - scope:
      path: "_observations"
      type: "observations"
    values:
      layout: "observation"